begin
  require 'rubygems'
  require 'jeweler'
  Jeweler::Tasks.new do |gemspec|
    gemspec.name = "metaq"
    gemspec.summary = "Metaq client for Ruby"
    gemspec.description = gemspec.summary
    gemspec.email = "killme2008@gmail.com"
    gemspec.homepage = "https://github.com/killme2008/Metamorphosis/tree/master/contrib/ruby/meta-ruby"
    gemspec.authors = ["Dennis Zhuang"]
    gemspec.files = Dir.glob('lib/**/*.rb')
    gemspec.add_dependency 'zookeeper','>= 1.2.2'
    gemspec.version = "0.1.0"
  end
rescue LoadError
  puts "Jeweler not available. Install it with: sudo gem install jeweler"
end
