// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransactionCommands.proto

package com.taobao.metamorphosis.server.transaction.store;

public final class TransactionCommands {
  private TransactionCommands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.taobao.tddl.dbproxy.protocol.TxCommandType}
   */
  public enum TxCommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>APPEND_MSG = 1;</code>
     */
    APPEND_MSG(0, 1),
    /**
     * <code>TX_OP = 2;</code>
     */
    TX_OP(1, 2),
    ;

    /**
     * <code>APPEND_MSG = 1;</code>
     */
    public static final int APPEND_MSG_VALUE = 1;
    /**
     * <code>TX_OP = 2;</code>
     */
    public static final int TX_OP_VALUE = 2;


    public final int getNumber() { return value; }

    public static TxCommandType valueOf(int value) {
      switch (value) {
        case 1: return APPEND_MSG;
        case 2: return TX_OP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TxCommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TxCommandType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TxCommandType>() {
            public TxCommandType findValueByNumber(int number) {
              return TxCommandType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.getDescriptor().getEnumTypes().get(0);
    }

    private static final TxCommandType[] VALUES = values();

    public static TxCommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TxCommandType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.taobao.tddl.dbproxy.protocol.TxCommandType)
  }

  /**
   * Protobuf enum {@code com.taobao.tddl.dbproxy.protocol.TransactionType}
   */
  public enum TransactionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>XA_PREPARE = 1;</code>
     */
    XA_PREPARE(0, 1),
    /**
     * <code>XA_COMMIT = 2;</code>
     */
    XA_COMMIT(1, 2),
    /**
     * <code>XA_ROLLBACK = 3;</code>
     */
    XA_ROLLBACK(2, 3),
    /**
     * <code>LOCAL_COMMIT = 4;</code>
     */
    LOCAL_COMMIT(3, 4),
    /**
     * <code>LOCAL_ROLLBACK = 5;</code>
     */
    LOCAL_ROLLBACK(4, 5),
    ;

    /**
     * <code>XA_PREPARE = 1;</code>
     */
    public static final int XA_PREPARE_VALUE = 1;
    /**
     * <code>XA_COMMIT = 2;</code>
     */
    public static final int XA_COMMIT_VALUE = 2;
    /**
     * <code>XA_ROLLBACK = 3;</code>
     */
    public static final int XA_ROLLBACK_VALUE = 3;
    /**
     * <code>LOCAL_COMMIT = 4;</code>
     */
    public static final int LOCAL_COMMIT_VALUE = 4;
    /**
     * <code>LOCAL_ROLLBACK = 5;</code>
     */
    public static final int LOCAL_ROLLBACK_VALUE = 5;


    public final int getNumber() { return value; }

    public static TransactionType valueOf(int value) {
      switch (value) {
        case 1: return XA_PREPARE;
        case 2: return XA_COMMIT;
        case 3: return XA_ROLLBACK;
        case 4: return LOCAL_COMMIT;
        case 5: return LOCAL_ROLLBACK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TransactionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TransactionType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TransactionType>() {
            public TransactionType findValueByNumber(int number) {
              return TransactionType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.getDescriptor().getEnumTypes().get(1);
    }

    private static final TransactionType[] VALUES = values();

    public static TransactionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TransactionType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.taobao.tddl.dbproxy.protocol.TransactionType)
  }

  public interface TxCommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.taobao.tddl.dbproxy.protocol.TxCommandType cmdType = 1;
    /**
     * <code>required .com.taobao.tddl.dbproxy.protocol.TxCommandType cmdType = 1;</code>
     */
    boolean hasCmdType();
    /**
     * <code>required .com.taobao.tddl.dbproxy.protocol.TxCommandType cmdType = 1;</code>
     */
    com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommandType getCmdType();

    // required bytes cmd_content = 2;
    /**
     * <code>required bytes cmd_content = 2;</code>
     */
    boolean hasCmdContent();
    /**
     * <code>required bytes cmd_content = 2;</code>
     */
    com.google.protobuf.ByteString getCmdContent();

    // optional bool force = 3 [default = false];
    /**
     * <code>optional bool force = 3 [default = false];</code>
     */
    boolean hasForce();
    /**
     * <code>optional bool force = 3 [default = false];</code>
     */
    boolean getForce();
  }
  /**
   * Protobuf type {@code com.taobao.tddl.dbproxy.protocol.TxCommand}
   */
  public static final class TxCommand extends
      com.google.protobuf.GeneratedMessage
      implements TxCommandOrBuilder {
    // Use TxCommand.newBuilder() to construct.
    private TxCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TxCommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TxCommand defaultInstance;
    public static TxCommand getDefaultInstance() {
      return defaultInstance;
    }

    public TxCommand getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TxCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommandType value = com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommandType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                cmdType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              cmdContent_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              force_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.internal_static_com_taobao_tddl_dbproxy_protocol_TxCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.internal_static_com_taobao_tddl_dbproxy_protocol_TxCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand.class, com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand.Builder.class);
    }

    public static com.google.protobuf.Parser<TxCommand> PARSER =
        new com.google.protobuf.AbstractParser<TxCommand>() {
      public TxCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TxCommand(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TxCommand> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.taobao.tddl.dbproxy.protocol.TxCommandType cmdType = 1;
    public static final int CMDTYPE_FIELD_NUMBER = 1;
    private com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommandType cmdType_;
    /**
     * <code>required .com.taobao.tddl.dbproxy.protocol.TxCommandType cmdType = 1;</code>
     */
    public boolean hasCmdType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.taobao.tddl.dbproxy.protocol.TxCommandType cmdType = 1;</code>
     */
    public com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommandType getCmdType() {
      return cmdType_;
    }

    // required bytes cmd_content = 2;
    public static final int CMD_CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString cmdContent_;
    /**
     * <code>required bytes cmd_content = 2;</code>
     */
    public boolean hasCmdContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes cmd_content = 2;</code>
     */
    public com.google.protobuf.ByteString getCmdContent() {
      return cmdContent_;
    }

    // optional bool force = 3 [default = false];
    public static final int FORCE_FIELD_NUMBER = 3;
    private boolean force_;
    /**
     * <code>optional bool force = 3 [default = false];</code>
     */
    public boolean hasForce() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool force = 3 [default = false];</code>
     */
    public boolean getForce() {
      return force_;
    }

    private void initFields() {
      cmdType_ = com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommandType.APPEND_MSG;
      cmdContent_ = com.google.protobuf.ByteString.EMPTY;
      force_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCmdType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmdContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, cmdType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, cmdContent_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, force_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, cmdType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, cmdContent_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, force_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.taobao.tddl.dbproxy.protocol.TxCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.internal_static_com_taobao_tddl_dbproxy_protocol_TxCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.internal_static_com_taobao_tddl_dbproxy_protocol_TxCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand.class, com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand.Builder.class);
      }

      // Construct using com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmdType_ = com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommandType.APPEND_MSG;
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdContent_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        force_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.internal_static_com_taobao_tddl_dbproxy_protocol_TxCommand_descriptor;
      }

      public com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand getDefaultInstanceForType() {
        return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand.getDefaultInstance();
      }

      public com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand build() {
        com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand buildPartial() {
        com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand result = new com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmdType_ = cmdType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cmdContent_ = cmdContent_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.force_ = force_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand) {
          return mergeFrom((com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand other) {
        if (other == com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand.getDefaultInstance()) return this;
        if (other.hasCmdType()) {
          setCmdType(other.getCmdType());
        }
        if (other.hasCmdContent()) {
          setCmdContent(other.getCmdContent());
        }
        if (other.hasForce()) {
          setForce(other.getForce());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCmdType()) {
          
          return false;
        }
        if (!hasCmdContent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.taobao.tddl.dbproxy.protocol.TxCommandType cmdType = 1;
      private com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommandType cmdType_ = com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommandType.APPEND_MSG;
      /**
       * <code>required .com.taobao.tddl.dbproxy.protocol.TxCommandType cmdType = 1;</code>
       */
      public boolean hasCmdType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.taobao.tddl.dbproxy.protocol.TxCommandType cmdType = 1;</code>
       */
      public com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommandType getCmdType() {
        return cmdType_;
      }
      /**
       * <code>required .com.taobao.tddl.dbproxy.protocol.TxCommandType cmdType = 1;</code>
       */
      public Builder setCmdType(com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        cmdType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.taobao.tddl.dbproxy.protocol.TxCommandType cmdType = 1;</code>
       */
      public Builder clearCmdType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdType_ = com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TxCommandType.APPEND_MSG;
        onChanged();
        return this;
      }

      // required bytes cmd_content = 2;
      private com.google.protobuf.ByteString cmdContent_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes cmd_content = 2;</code>
       */
      public boolean hasCmdContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes cmd_content = 2;</code>
       */
      public com.google.protobuf.ByteString getCmdContent() {
        return cmdContent_;
      }
      /**
       * <code>required bytes cmd_content = 2;</code>
       */
      public Builder setCmdContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cmdContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes cmd_content = 2;</code>
       */
      public Builder clearCmdContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cmdContent_ = getDefaultInstance().getCmdContent();
        onChanged();
        return this;
      }

      // optional bool force = 3 [default = false];
      private boolean force_ ;
      /**
       * <code>optional bool force = 3 [default = false];</code>
       */
      public boolean hasForce() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool force = 3 [default = false];</code>
       */
      public boolean getForce() {
        return force_;
      }
      /**
       * <code>optional bool force = 3 [default = false];</code>
       */
      public Builder setForce(boolean value) {
        bitField0_ |= 0x00000004;
        force_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool force = 3 [default = false];</code>
       */
      public Builder clearForce() {
        bitField0_ = (bitField0_ & ~0x00000004);
        force_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.taobao.tddl.dbproxy.protocol.TxCommand)
    }

    static {
      defaultInstance = new TxCommand(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.taobao.tddl.dbproxy.protocol.TxCommand)
  }

  public interface AppendMessageCommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 message_id = 1;
    /**
     * <code>required int64 message_id = 1;</code>
     */
    boolean hasMessageId();
    /**
     * <code>required int64 message_id = 1;</code>
     */
    long getMessageId();

    // required bytes put_command = 2;
    /**
     * <code>required bytes put_command = 2;</code>
     */
    boolean hasPutCommand();
    /**
     * <code>required bytes put_command = 2;</code>
     */
    com.google.protobuf.ByteString getPutCommand();
  }
  /**
   * Protobuf type {@code com.taobao.tddl.dbproxy.protocol.AppendMessageCommand}
   */
  public static final class AppendMessageCommand extends
      com.google.protobuf.GeneratedMessage
      implements AppendMessageCommandOrBuilder {
    // Use AppendMessageCommand.newBuilder() to construct.
    private AppendMessageCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AppendMessageCommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AppendMessageCommand defaultInstance;
    public static AppendMessageCommand getDefaultInstance() {
      return defaultInstance;
    }

    public AppendMessageCommand getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AppendMessageCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              messageId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              putCommand_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.internal_static_com_taobao_tddl_dbproxy_protocol_AppendMessageCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.internal_static_com_taobao_tddl_dbproxy_protocol_AppendMessageCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand.class, com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand.Builder.class);
    }

    public static com.google.protobuf.Parser<AppendMessageCommand> PARSER =
        new com.google.protobuf.AbstractParser<AppendMessageCommand>() {
      public AppendMessageCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppendMessageCommand(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AppendMessageCommand> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 message_id = 1;
    public static final int MESSAGE_ID_FIELD_NUMBER = 1;
    private long messageId_;
    /**
     * <code>required int64 message_id = 1;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 message_id = 1;</code>
     */
    public long getMessageId() {
      return messageId_;
    }

    // required bytes put_command = 2;
    public static final int PUT_COMMAND_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString putCommand_;
    /**
     * <code>required bytes put_command = 2;</code>
     */
    public boolean hasPutCommand() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes put_command = 2;</code>
     */
    public com.google.protobuf.ByteString getPutCommand() {
      return putCommand_;
    }

    private void initFields() {
      messageId_ = 0L;
      putCommand_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMessageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPutCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, putCommand_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, putCommand_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.taobao.tddl.dbproxy.protocol.AppendMessageCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.internal_static_com_taobao_tddl_dbproxy_protocol_AppendMessageCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.internal_static_com_taobao_tddl_dbproxy_protocol_AppendMessageCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand.class, com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand.Builder.class);
      }

      // Construct using com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        putCommand_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.internal_static_com_taobao_tddl_dbproxy_protocol_AppendMessageCommand_descriptor;
      }

      public com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand getDefaultInstanceForType() {
        return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand.getDefaultInstance();
      }

      public com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand build() {
        com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand buildPartial() {
        com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand result = new com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.putCommand_ = putCommand_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand) {
          return mergeFrom((com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand other) {
        if (other == com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand.getDefaultInstance()) return this;
        if (other.hasMessageId()) {
          setMessageId(other.getMessageId());
        }
        if (other.hasPutCommand()) {
          setPutCommand(other.getPutCommand());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageId()) {
          
          return false;
        }
        if (!hasPutCommand()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.taobao.metamorphosis.server.transaction.store.TransactionCommands.AppendMessageCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 message_id = 1;
      private long messageId_ ;
      /**
       * <code>required int64 message_id = 1;</code>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 message_id = 1;</code>
       */
      public long getMessageId() {
        return messageId_;
      }
      /**
       * <code>required int64 message_id = 1;</code>
       */
      public Builder setMessageId(long value) {
        bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 message_id = 1;</code>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = 0L;
        onChanged();
        return this;
      }

      // required bytes put_command = 2;
      private com.google.protobuf.ByteString putCommand_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes put_command = 2;</code>
       */
      public boolean hasPutCommand() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes put_command = 2;</code>
       */
      public com.google.protobuf.ByteString getPutCommand() {
        return putCommand_;
      }
      /**
       * <code>required bytes put_command = 2;</code>
       */
      public Builder setPutCommand(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        putCommand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes put_command = 2;</code>
       */
      public Builder clearPutCommand() {
        bitField0_ = (bitField0_ & ~0x00000002);
        putCommand_ = getDefaultInstance().getPutCommand();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.taobao.tddl.dbproxy.protocol.AppendMessageCommand)
    }

    static {
      defaultInstance = new AppendMessageCommand(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.taobao.tddl.dbproxy.protocol.AppendMessageCommand)
  }

  public interface TransactionOperationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.taobao.tddl.dbproxy.protocol.TransactionType type = 1;
    /**
     * <code>required .com.taobao.tddl.dbproxy.protocol.TransactionType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.taobao.tddl.dbproxy.protocol.TransactionType type = 1;</code>
     */
    com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionType getType();

    // required bool was_prepared = 2;
    /**
     * <code>required bool was_prepared = 2;</code>
     */
    boolean hasWasPrepared();
    /**
     * <code>required bool was_prepared = 2;</code>
     */
    boolean getWasPrepared();

    // required string transaction_id = 3;
    /**
     * <code>required string transaction_id = 3;</code>
     */
    boolean hasTransactionId();
    /**
     * <code>required string transaction_id = 3;</code>
     */
    java.lang.String getTransactionId();
    /**
     * <code>required string transaction_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getTransactionIdBytes();

    // optional int32 data_length = 4;
    /**
     * <code>optional int32 data_length = 4;</code>
     *
     * <pre>
     *额外数据的长度
     * </pre>
     */
    boolean hasDataLength();
    /**
     * <code>optional int32 data_length = 4;</code>
     *
     * <pre>
     *额外数据的长度
     * </pre>
     */
    int getDataLength();
  }
  /**
   * Protobuf type {@code com.taobao.tddl.dbproxy.protocol.TransactionOperation}
   */
  public static final class TransactionOperation extends
      com.google.protobuf.GeneratedMessage
      implements TransactionOperationOrBuilder {
    // Use TransactionOperation.newBuilder() to construct.
    private TransactionOperation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TransactionOperation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TransactionOperation defaultInstance;
    public static TransactionOperation getDefaultInstance() {
      return defaultInstance;
    }

    public TransactionOperation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TransactionOperation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionType value = com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              wasPrepared_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              transactionId_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              dataLength_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.internal_static_com_taobao_tddl_dbproxy_protocol_TransactionOperation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.internal_static_com_taobao_tddl_dbproxy_protocol_TransactionOperation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation.class, com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation.Builder.class);
    }

    public static com.google.protobuf.Parser<TransactionOperation> PARSER =
        new com.google.protobuf.AbstractParser<TransactionOperation>() {
      public TransactionOperation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransactionOperation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionOperation> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.taobao.tddl.dbproxy.protocol.TransactionType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionType type_;
    /**
     * <code>required .com.taobao.tddl.dbproxy.protocol.TransactionType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.taobao.tddl.dbproxy.protocol.TransactionType type = 1;</code>
     */
    public com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionType getType() {
      return type_;
    }

    // required bool was_prepared = 2;
    public static final int WAS_PREPARED_FIELD_NUMBER = 2;
    private boolean wasPrepared_;
    /**
     * <code>required bool was_prepared = 2;</code>
     */
    public boolean hasWasPrepared() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool was_prepared = 2;</code>
     */
    public boolean getWasPrepared() {
      return wasPrepared_;
    }

    // required string transaction_id = 3;
    public static final int TRANSACTION_ID_FIELD_NUMBER = 3;
    private java.lang.Object transactionId_;
    /**
     * <code>required string transaction_id = 3;</code>
     */
    public boolean hasTransactionId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string transaction_id = 3;</code>
     */
    public java.lang.String getTransactionId() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          transactionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string transaction_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTransactionIdBytes() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 data_length = 4;
    public static final int DATA_LENGTH_FIELD_NUMBER = 4;
    private int dataLength_;
    /**
     * <code>optional int32 data_length = 4;</code>
     *
     * <pre>
     *额外数据的长度
     * </pre>
     */
    public boolean hasDataLength() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 data_length = 4;</code>
     *
     * <pre>
     *额外数据的长度
     * </pre>
     */
    public int getDataLength() {
      return dataLength_;
    }

    private void initFields() {
      type_ = com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionType.XA_PREPARE;
      wasPrepared_ = false;
      transactionId_ = "";
      dataLength_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWasPrepared()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTransactionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, wasPrepared_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTransactionIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, dataLength_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, wasPrepared_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTransactionIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, dataLength_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.taobao.tddl.dbproxy.protocol.TransactionOperation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.internal_static_com_taobao_tddl_dbproxy_protocol_TransactionOperation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.internal_static_com_taobao_tddl_dbproxy_protocol_TransactionOperation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation.class, com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation.Builder.class);
      }

      // Construct using com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionType.XA_PREPARE;
        bitField0_ = (bitField0_ & ~0x00000001);
        wasPrepared_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        transactionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        dataLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.internal_static_com_taobao_tddl_dbproxy_protocol_TransactionOperation_descriptor;
      }

      public com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation getDefaultInstanceForType() {
        return com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation.getDefaultInstance();
      }

      public com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation build() {
        com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation buildPartial() {
        com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation result = new com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.wasPrepared_ = wasPrepared_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.transactionId_ = transactionId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dataLength_ = dataLength_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation) {
          return mergeFrom((com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation other) {
        if (other == com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasWasPrepared()) {
          setWasPrepared(other.getWasPrepared());
        }
        if (other.hasTransactionId()) {
          bitField0_ |= 0x00000004;
          transactionId_ = other.transactionId_;
          onChanged();
        }
        if (other.hasDataLength()) {
          setDataLength(other.getDataLength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasWasPrepared()) {
          
          return false;
        }
        if (!hasTransactionId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionOperation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.taobao.tddl.dbproxy.protocol.TransactionType type = 1;
      private com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionType type_ = com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionType.XA_PREPARE;
      /**
       * <code>required .com.taobao.tddl.dbproxy.protocol.TransactionType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.taobao.tddl.dbproxy.protocol.TransactionType type = 1;</code>
       */
      public com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionType getType() {
        return type_;
      }
      /**
       * <code>required .com.taobao.tddl.dbproxy.protocol.TransactionType type = 1;</code>
       */
      public Builder setType(com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.taobao.tddl.dbproxy.protocol.TransactionType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.taobao.metamorphosis.server.transaction.store.TransactionCommands.TransactionType.XA_PREPARE;
        onChanged();
        return this;
      }

      // required bool was_prepared = 2;
      private boolean wasPrepared_ ;
      /**
       * <code>required bool was_prepared = 2;</code>
       */
      public boolean hasWasPrepared() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool was_prepared = 2;</code>
       */
      public boolean getWasPrepared() {
        return wasPrepared_;
      }
      /**
       * <code>required bool was_prepared = 2;</code>
       */
      public Builder setWasPrepared(boolean value) {
        bitField0_ |= 0x00000002;
        wasPrepared_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool was_prepared = 2;</code>
       */
      public Builder clearWasPrepared() {
        bitField0_ = (bitField0_ & ~0x00000002);
        wasPrepared_ = false;
        onChanged();
        return this;
      }

      // required string transaction_id = 3;
      private java.lang.Object transactionId_ = "";
      /**
       * <code>required string transaction_id = 3;</code>
       */
      public boolean hasTransactionId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string transaction_id = 3;</code>
       */
      public java.lang.String getTransactionId() {
        java.lang.Object ref = transactionId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          transactionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string transaction_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTransactionIdBytes() {
        java.lang.Object ref = transactionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transactionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string transaction_id = 3;</code>
       */
      public Builder setTransactionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        transactionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string transaction_id = 3;</code>
       */
      public Builder clearTransactionId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        transactionId_ = getDefaultInstance().getTransactionId();
        onChanged();
        return this;
      }
      /**
       * <code>required string transaction_id = 3;</code>
       */
      public Builder setTransactionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        transactionId_ = value;
        onChanged();
        return this;
      }

      // optional int32 data_length = 4;
      private int dataLength_ ;
      /**
       * <code>optional int32 data_length = 4;</code>
       *
       * <pre>
       *额外数据的长度
       * </pre>
       */
      public boolean hasDataLength() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 data_length = 4;</code>
       *
       * <pre>
       *额外数据的长度
       * </pre>
       */
      public int getDataLength() {
        return dataLength_;
      }
      /**
       * <code>optional int32 data_length = 4;</code>
       *
       * <pre>
       *额外数据的长度
       * </pre>
       */
      public Builder setDataLength(int value) {
        bitField0_ |= 0x00000008;
        dataLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 data_length = 4;</code>
       *
       * <pre>
       *额外数据的长度
       * </pre>
       */
      public Builder clearDataLength() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dataLength_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.taobao.tddl.dbproxy.protocol.TransactionOperation)
    }

    static {
      defaultInstance = new TransactionOperation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.taobao.tddl.dbproxy.protocol.TransactionOperation)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_taobao_tddl_dbproxy_protocol_TxCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_taobao_tddl_dbproxy_protocol_TxCommand_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_taobao_tddl_dbproxy_protocol_AppendMessageCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_taobao_tddl_dbproxy_protocol_AppendMessageCommand_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_taobao_tddl_dbproxy_protocol_TransactionOperation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_taobao_tddl_dbproxy_protocol_TransactionOperation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031TransactionCommands.proto\022 com.taobao." +
      "tddl.dbproxy.protocol\"x\n\tTxCommand\022@\n\007cm" +
      "dType\030\001 \002(\0162/.com.taobao.tddl.dbproxy.pr" +
      "otocol.TxCommandType\022\023\n\013cmd_content\030\002 \002(" +
      "\014\022\024\n\005force\030\003 \001(\010:\005false\"?\n\024AppendMessage" +
      "Command\022\022\n\nmessage_id\030\001 \002(\003\022\023\n\013put_comma" +
      "nd\030\002 \002(\014\"\232\001\n\024TransactionOperation\022?\n\004typ" +
      "e\030\001 \002(\01621.com.taobao.tddl.dbproxy.protoc" +
      "ol.TransactionType\022\024\n\014was_prepared\030\002 \002(\010" +
      "\022\026\n\016transaction_id\030\003 \002(\t\022\023\n\013data_length\030",
      "\004 \001(\005**\n\rTxCommandType\022\016\n\nAPPEND_MSG\020\001\022\t" +
      "\n\005TX_OP\020\002*g\n\017TransactionType\022\016\n\nXA_PREPA" +
      "RE\020\001\022\r\n\tXA_COMMIT\020\002\022\017\n\013XA_ROLLBACK\020\003\022\020\n\014" +
      "LOCAL_COMMIT\020\004\022\022\n\016LOCAL_ROLLBACK\020\005BJ\n1co" +
      "m.taobao.metamorphosis.server.transactio" +
      "n.storeB\023TransactionCommandsH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_taobao_tddl_dbproxy_protocol_TxCommand_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_taobao_tddl_dbproxy_protocol_TxCommand_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_taobao_tddl_dbproxy_protocol_TxCommand_descriptor,
              new java.lang.String[] { "CmdType", "CmdContent", "Force", });
          internal_static_com_taobao_tddl_dbproxy_protocol_AppendMessageCommand_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_taobao_tddl_dbproxy_protocol_AppendMessageCommand_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_taobao_tddl_dbproxy_protocol_AppendMessageCommand_descriptor,
              new java.lang.String[] { "MessageId", "PutCommand", });
          internal_static_com_taobao_tddl_dbproxy_protocol_TransactionOperation_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_taobao_tddl_dbproxy_protocol_TransactionOperation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_taobao_tddl_dbproxy_protocol_TransactionOperation_descriptor,
              new java.lang.String[] { "Type", "WasPrepared", "TransactionId", "DataLength", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
